### ISSUE TITLE
Bookdown

### ISSUE THREAD

**Issue by rosstox26** [jwo1234/MBAN501#1]
As a priority task, you would want to install the Bookdown package and create the demo bookdown "book" - you will then be able to edit the demo book to create your content.

**Comment by rosstox26** [comment]
Any update folks?

**Comment by rosstox26** [comment]
Folks - I see that you have bookdown installed correctly. You still need a couple minor tweaks:

The output folder has to be called "docs". You need to make the following change for it to be created.

See the last line of this file: https://github.com/nklobo-mban/EffectiveCommunication/blob/main/_bookdown.yml

Then you can go to settings -> pages and set the pages location to main branch and docs folder. Then you should be able to see your published site.

**Comment by rosstox26** [comment]
I see that your docs folder exists and your published site is working. You should add a link to the site in your readme.

I am closing this issue.

**Comment by zjl198** [comment]
The published site is working now. Thanks Sanjeev! We will make the change on readme as well.

**Comment by rosstox26** [comment]
perfect, I am closing this issue,
